//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public string mid { get; set; }
        public string mname { get; set; }
        public string repository_id { get; set; }
        public int rest { get; set; }
        public int category_id { get; set; }
        public Nullable<double> price { get; set; }
    }
}
