//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialOT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MmsContext : DbContext
    {
        public MmsContext()
            : base("name=MmsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<in_item> in_item { get; set; }
        public virtual DbSet<in_order> in_order { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<out_item> out_item { get; set; }
        public virtual DbSet<out_order> out_order { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
