//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialOT
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string user_id { get; set; }
        public string emplyee_id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public Nullable<int> sex { get; set; }
        public string phone { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> age { get; set; }
        public int type { get; set; }
    }
}
